### PR TITLE
Shared component migration

### PR DESCRIPTION
**Pull request by logic0319**

### CODE REVIEW

**Review by geoseong — COMMENTED** [review]
Nice work!! welcome to dooboolab 👍
@hyochan , these commits are right behind the commits at `march, 14th`.
but in this main repository, there are more several another commits after `march, 14th`.
Is it okay to merge? I'm afraid there would be conflict or made complicated commit graph.
I want to hear your thoughts.

**Review by hyochan — CHANGES_REQUESTED** [review]
Could you check if you've had `rebased` this?

**Comment by logic0319** [comment]
Um...don't merge my pull request. 
I made duplicated commits. I am not used to using rebase.
This is what i do for rebasing.
1. from my local master branch `git pull upstream master`
2. from my local shared-component-migration branch `git rebase master`
3. from my local shared-component-migration branch `git push origin shared-component-migration`
but git required me to pull the branch first. so I pull the branch and try again push.
Then..duplicated commits were made.
could you let me know which part did i wrong?

**Comment by hyochan** [comment]
@YongPilMoon You can refer to [CONTRIBUTING GUIDE](https://github.com/dooboolab/talktalk-rn/blob/master/CONTRIBUTING.md).
1. Try rebasing your master branch with upstream (Make sure you have set `upstream` correctly).
   ```
   $ git fetch upstream && git rebase upstream/master
   ```
2. Rebase to your master branch from your working branch.
   ```
   $ git checkout shared-component-migration
   $ git rebase master
   ```
3. Resolve conflict if it alerts you anything. Or else, you are done.

**Comment by hyochan** [comment]
@YongPilMoon @geoseong Since there is no conflict with master branch, you don't have to worry about `rebasing` though. I can do this in `github`. However, I'll take time merging this for your practice. I'll try merging tomorrow.

**Comment by hyochan** [comment]
@YongPilMoon I am seeing duplicate commits.
Screen Shot 2019-03-20 at 6 03 01 PM

Could you simplify your commits with no `duplicate`? You can simply `hard --reset` or create new `branch`.

**Comment by logic0319** [comment]
I removed duplicated commit and rebased on the latest code without conflict. Thanks for your help.

**Review by hyochan — APPROVED** [review]
Good work! Thank you for your contribution.

**Comment by hyochan** [comment]
@all-contributors please add @YongPilMoon for code

**Comment by hyochan** [comment]
@YongPilMoon Could you also try out for implementing `test code` using `jest` and `react-native-testing-library`?

**Pull request merged**
